# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-tutorial',
                'doc_host': 'https://AdityaVarmaUddaraju.github.io',
                'git_url': 'https://github.com/AdityaVarmaUddaraju/nbdev-tutorial',
                'lib_path': 'nbdev_tutorial'},
  'syms': { 'nbdev_tutorial.core': { 'nbdev_tutorial.core.foo': ('core.html#foo', 'nbdev_tutorial/core.py'),
                                     'nbdev_tutorial.core.say_hello': ('core.html#say_hello', 'nbdev_tutorial/core.py')}}}
